version: "3.9"
services:
  ecommerce:
    image: ecommerce:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 10s
      # healthcheck:
      #   test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      #   start_period: 30s
      #   interval: 10s
      #   timeout: 3s
      #   retries: 2
    networks:
      - app-network

  exchange:
    image: exchange:latest
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        window: 10s
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 2
    networks:
      - app-network

  fidelity:
    image: fidelity:latest
    ports:
      - "8082:8082"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 10s
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 2
    networks:
      - app-network

  store:
    image: store:latest
    ports:
      - "8083:8083"
    deploy:
      replicas: 4
      restart_policy:
        condition: any
        window: 10s
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 2
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
